spring:
  application:
    name: hello-spring-cloud-config

  boot:
      admin:
        client:
          url: http://localhost:8084

  cloud:
    config:
      label: master
      server:
        git:
          uri: http://10.3.131.136/twg/spring-cloud-config.git
          search-paths: respo
          username: twg
          password: 12345678
  zipkin:
      base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/